#!/usr/bin/env bash

# Author: Jason Mumbulla (jasonmumbulla@gmail.com)
APPNAME="BiodiverseGUI"

DIR="$(cd "$(dirname "$0")" && pwd -P)"

DATETIME=$(date +%y%m%d-%H:%M:%S)
LOG_FILE="$HOME/Library/Logs/$APPNAME/${APPNAME}-${DATETIME}.log"

# Create the log file directory if it doesn't exist
mkdir -p "`dirname \"$LOG_FILE\"`"

# create the Gtk file history dir
[ -d "$HOME/.local/share" ] || mkdir -p "$HOME/.local/share"

# Run the app and redirect standard 
# output and error to the log file.
exec $DIR/$APPNAME >> $LOG_FILE 2>&1
