name: macos

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

env:
  PERL5LIB: /Users/runner/perl5/lib/perl5
  PERL_LOCAL_LIB_ROOT: /Users/runner/perl5
  PERL_MB_OPT: --install_base /Users/runner/perl5
  PERL_MM_OPT: INSTALL_BASE=/Users/runner/perl5

jobs:
  perl:

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Probe wd
        run: |
          pwd
          ls -l
          
      - name: Probe /usr/lib etc
        run: |
          echo /usr/local
          ls /usr/local
          echo /usr/lib/
          ls /usr/lib/
          echo /usr/lib/system
          ls /usr/lib/system
          

        
      - name: Set up Perl
        run: |
          \curl -L https://install.perlbrew.pl | bash
          source ~/perl5/perlbrew/etc/bashrc
          which -a perlbrew
          perlbrew init
          perlbrew install-cpanm
          perlbrew install-patchperl
          perlbrew install --noman -j 2 perl-5.30.1
          cat ~/perl5/perlbrew/build.perl-5.30.1.log
          perlbrew switch perl-5.30.1
          echo "##[add-path]/Users/runner/perl5/bin"

      - name: perl -V
        run: perl -V

      - name: Install pkgconfig
        run: brew install pkgconfig

      - name: Install GDAL and its deps
        run: brew install gdal
        
      #- name: Get lib names
      #  run: |
      #    find /usr/local/Cellar -name '*.dylib' -print
      #    find /usr/local/Cellar -name 'libxml2*.dylib' -print
      #    find /usr/local/Cellar -name '*lwgeom*.dylib' -print
      #    find /usr/local/Cellar -name 'libsqlite3*.dylib' -print
          
        
      - name: Install Gtk etc
        run: brew install gdk-pixbuf pango gtk+ gtk+3
      
      - name: Install libgnomecanvas and cuckoo our patched dylib across
        run: |
          brew install libgnomecanvas
          sudo cp libgnomecanvas-2.0.dylib /usr/local/Cellar/libgnomecanvas/2.30.3_4/lib/libgnomecanvas-2.0.dylib
          ls -lR /usr/local/Cellar/libgnomecanvas/2.30.3_4/lib
        
      #- name: otool probe
      #  run: |
      #    otool -L /usr/local/opt/gdal/lib/libgdal.20.dylib
      #    otool -L /usr/local/opt/glib/lib/libgobject-2.0.0.dylib
      #    otool -L /usr/local/opt/glib/lib/libglib-2.0.0.dylib
      #    otool -L /usr/local/opt/libffi/lib/libffi.6.dylib
      #    otool -L /usr/local/opt/pango/lib/libpango-1.0.0.dylib
      #    otool -L /usr/local/opt/pango/lib/libpangocairo-1.0.0.dylib
      #    otool -L /usr/local/opt/cairo/lib/libcairo.2.dylib
      #    otool -L /usr/local/opt/freetype/lib/libfreetype.6.dylib
      #    otool -L /usr/local/opt/glib/lib/libgthread-2.0.0.dylib
      #    otool -L /usr/local/opt/pcre1/lib/libpcre.1.dylib
      #    otool -L /usr/local/opt/gettext/lib/libintl.8.dylib
      #    otool -L /usr/local/opt/pango/lib/libpangoft2-1.0.0.dylib
      #    otool -L /usr/local/opt/harfbuzz/lib/libharfbuzz.0.dylib
      #    otool -L /usr/local/opt/fontconfig/lib/libfontconfig.1.dylib
      #    otool -L /usr/local/opt/pixman/lib/libpixman-1.0.dylib
      #    otool -L /usr/local/opt/libpng/lib/libpng16.16.dylib
      #    otool -L /usr/local/opt/gtk+/lib/libgtk-quartz-2.0.0.dylib
      #    otool -L /usr/local/opt/gtk+/lib/libgdk-quartz-2.0.0.dylib
      #    otool -L /usr/local/opt/atk/lib/libatk-1.0.0.dylib
      #    otool -L /usr/local/opt/gdk-pixbuf/lib/libgdk_pixbuf-2.0.0.dylib
      #    otool -L /usr/local/opt/glib/lib/libgio-2.0.0.dylib
      #    otool -L /usr/local/opt/glib/lib/libgmodule-2.0.0.dylib
      #    otool -L /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
      #    otool -L /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
      #    otool -L /usr/local/opt/proj/lib/libproj.15.dylib
      #    otool -L /usr/local/opt/json-c/lib/libjson-c.4.dylib
      #    otool -L /usr/local/opt/freexl/lib/libfreexl.1.dylib
      #    otool -L /usr/local/opt/geos/lib/libgeos_c.1.dylib
      #    otool -L /usr/local/opt/giflib/lib/libgif.7.dylib
      #    otool -L /usr/local/opt/libjpeg/lib/libjpeg.9.dylib
      #    otool -L /usr/local/opt/libgeotiff/lib/libgeotiff.5.dylib
      #    otool -L /usr/local/opt/libtiff/lib/libtiff.5.dylib
      #    otool -L /usr/local/opt/libspatialite/lib/libspatialite.7.dylib
      #    otool -L /usr/local/opt/geos/lib/libgeos-3.8.0.dylib
      #    otool -L libgnomecanvas-2.0.dylib
      #    otool -L /usr/local/opt/libart/lib/libart_lgpl_2.2.dylib
      #    otool -L /usr/local/opt/gtk+/lib/libgailutil.18.dylib
      #    otool -L /usr/local/opt/fribidi/lib/libfribidi.0.dylib
      #    otool -L /usr/local/opt/pzstd/lib/libzstd.1.dylib
      #    otool -L /usr/local/Cellar/libxml2/2.9.10/lib/libxml2.2.dylib
      #    otool -L /usr/local/Cellar/sqlite/3.31.1/lib/libsqlite3.0.dylib
      #    otool -L /usr/local/opt/graphite2/lib/libgraphite2.3.dylib

      - name: Prepare for cache
        run: |
          perl -V > perlversion.txt
          echo "cache perlbrew 20200304" > perlversion.txt
          #  change the checksum to refresh the cache
          echo 'with shared Alien installs' >> perlversion.txt
          ls -l perlversion.txt

      #- name: clear cache
      #  run: rm ~/perl5/${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}

      - name: Cache CPAN modules
        uses: actions/cache@v1
        with:
          path: ~/perl5
          key: ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}

      - name: Install cpan deps 
        run: |
          #  no share install for Alien::MSYS
          cpanm --notest Alien::MSYS
          #  ensure share install for gdal et al
          ALIEN_INSTALL_TYPE=share cpanm --notest --installdeps Alien::gdal
          ALIEN_INSTALL_TYPE=share cpanm --notest -v Alien::gdal
          #ALIEN_INSTALL_TYPE=share cpanm --notest -v https://github.com/shawnlaffan/perl-alien-gdal.git
          cpanm --notest Task::Biodiverse::NoGUI
          cpanm --notest ExtUtils::PkgConfig
          cpanm --notest ExtUtils::Depends
          cpanm --notest Gtk2
          cpanm --notest Gnome2::Canvas
          cpanm --notest Task::Biodiverse
          cpanm --notest PAR::Packer
          cpanm --notest File::BaseDir
          cpanm --notest File::Find::Rule
      
      - name: pack gdal script
        run: |
          echo "========"
          perl pp_gdal_check.pl
          echo "========"
          echo Running packed exe
          ./pp_gdal_check
          echo "========"
          echo Running with /usr/local dirs out of the way
          sudo mv /usr/local/opt /usr/local/optx
          sudo mv /usr/local/Cellar /usr/local/Cellarx
          ./pp_gdal_check
          echo Putting /usr/local dirs back
          sudo mv /usr/local/optx /usr/local/opt
          sudo mv /usr/local/Cellarx /usr/local/Cellar
          echo "========"
          
      - name: Upload checkpp artefact
        uses: actions/upload-artifact@v1
        with:
          name: pp_gdal_check
          #path: ${DMG_FILE_NAME}
          path: ./pp_gdal_check
      
      - name: Test pack
        run: |
          #ls -l /usr/local/lib/../Cellar/gdal/2.4.4/lib/libgdal.20.dylib
          #ls -l /usr/local/opt/gdal/2.4.4/lib/libgdal.20.dylib
          echo Running perl dynamic_libs check
          perl -e 'use 5.020; use Geo::GDAL::FFI; say join ":", Alien::gdal->dynamic_libs'
          pp -M Alien::gdal -M Alien::proj -M Alien::geos::af -M Alien::sqlite -M FFI::CheckLib -e 'use 5.020; use Alien::gdal; say join ":", Alien::gdal->dynamic_libs' -o checkpp
          echo Running checkpp dynamic libs check
          ./checkpp
          echo Running checkpp with /usr/local dirs out of the way
          sudo mv /usr/local/opt /usr/local/optx
          sudo mv /usr/local/Cellar /usr/local/Cellarx
          ./checkpp
          echo Putting /usr/local dirs back
          sudo mv /usr/local/optx /usr/local/opt
          sudo mv /usr/local/Cellarx /usr/local/Cellar
          
          
      - name: Alien O'Toole
        run: |
          otool -L /Users/runner/perl5/lib/perl5/darwin-thread-multi-2level/auto/share/dist/Alien-gdal/lib/libgdal.dylib
          otool -L /Users/runner/perl5/lib/perl5/darwin-thread-multi-2level/auto/share/dist/Alien-gdal/lib/libgdal.26.dylib
          otool -L /Users/runner/perl5/lib/perl5/darwin-thread-multi-2level/auto/share/dist/Alien-geos-af/lib/libgeos.dylib
          otool -L /Users/runner/perl5/lib/perl5/darwin-thread-multi-2level/auto/share/dist/Alien-geos-af/lib/libgeos_c.dylib
          otool -L /Users/runner/perl5/lib/perl5/darwin-thread-multi-2level/auto/share/dist/Alien-sqlite/lib/libsqlite3.dylib
          otool -L /Users/runner/perl5/lib/perl5/darwin-thread-multi-2level/auto/share/dist/Alien-sqlite/lib/libsqlite3.0.dylib
          otool -L /Users/runner/perl5/lib/perl5/darwin-thread-multi-2level/auto/share/dist/Alien-proj/lib/libproj.dylib
          otool -L /Users/runner/perl5/lib/perl5/darwin-thread-multi-2level/auto/share/dist/Alien-proj/lib/libproj.19.dylib
        
      - name: Upload checkpp artefact
        uses: actions/upload-artifact@v1
        with:
          name: checkpp
          #path: ${DMG_FILE_NAME}
          path: ./checkpp

      - name: Clone biodiverse repo
        run: git clone https://github.com/shawnlaffan/biodiverse.git
        
      #- name: Check Biodiverse can run
      #  run: prove -l biodiverse/t
      
      - name: Resize dmg file
        run: hdiutil resize -size 75MB ./images/Biodiverse.dmg
      
      - name: Run mmb3.pl
        run: perl bin/mmb3.pl -v -s biodiverse/bin/BiodiverseGUI.pl
        
      - name: Find dmg file
        run: |
          export DMG_FILE_NAME=`find ./builds -name Biodiverse-*.dmg -print`
          echo ${DMG_FILE_NAME}
          
      - name: Try to run the app
        run: |
          echo With system /usr/loca/opt in path
          BDV_PP_BUILDING=1 ./builds/Biodiverse.app/Contents/MacOS/BiodiverseGUI
          #  we need the brewed libs out of the way for this check
          echo Moving /usr/local/lib
          sudo mv /usr/local/lib /usr/local/libx
          BDV_PP_BUILDING=1 ./builds/Biodiverse.app/Contents/MacOS/BiodiverseGUI
          echo Returning /usr/local/lib
          sudo mv /usr/local/libx /usr/local/lib
          
        
      - name: Upload artefact
        uses: actions/upload-artifact@v1
        with:
          name: dmg-file
          #path: ${DMG_FILE_NAME}
          path: ./builds/Biodiverse-3.00-2.dmg
