name: macos

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

env:
  PERL5LIB: /Users/runner/perl5/lib/perl5
  PERL_LOCAL_LIB_ROOT: /Users/runner/perl5
  PERL_MB_OPT: --install_base /Users/runner/perl5
  PERL_MM_OPT: INSTALL_BASE=/Users/runner/perl5

jobs:
  perl:

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Probe wd
        run: |
          pwd
          ls -l
          
      - name: Probe /usr/lib etc
        run: |
          echo /usr/local
          ls /usr/local
          echo /usr/lib/
          ls /usr/lib/
          echo /usr/lib/system
          ls /usr/lib/system
          

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: perlbrew_log
          path: /Users/runner/perl5/perlbrew/build.perl-5.30.1.log

      - name: Install pkgconfig
        run: brew install pkgconfig

      - name: Install GDAL and its deps
        run: brew install gdal

        
      - name: Install Gtk etc
        run: brew install gdk-pixbuf pango gtk+ gtk+3
      
      - name: Install libgnomecanvas and cuckoo our patched dylib across
        run: |
          brew install libgnomecanvas
          sudo cp libgnomecanvas-2.0.dylib /usr/local/Cellar/libgnomecanvas/2.30.3_4/lib/libgnomecanvas-2.0.dylib
          ls -lR /usr/local/Cellar/libgnomecanvas/2.30.3_4/lib
        
      

      - name: Prepare for perl cache
        run: |
          echo "cache perlbrew 20200304b" > perlversion.txt
          #  change the checksum to refresh the cache
          echo 'with shared Alien installs' >> perlversion.txt
          ls -l perlversion.txt

      #- name: clear cache
      #  run: rm ~/perl5/${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}

      - name: Perl5 cache
        uses: actions/cache@v1
        with:
          path: ~/perl5
          key: ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}

        
      - name: Set up Perl
        run: |
          echo Shell is $SHELL
          \curl -L https://install.perlbrew.pl | bash
          source ~/perl5/perlbrew/etc/bashrc
          which -a perlbrew
          perlbrew init
          perlbrew install-cpanm
          which cpanm
          #perlbrew install-patchperl
          #  we get 5.30 test failures due to https://github.com/Perl/perl5/pull/24
          #  but we can ignore them
          [ -d ~/perl5/perlbrew/perls/perl-5.30.1 ] || perlbrew install --notest --noman -j 2 perl-5.30.1
          perlbrew switch perl-5.30.1
          echo "##[add-path]/Users/runner/perl5/bin"


      - name: Install cpan deps 
        run: |
          source ~/perl5/perlbrew/etc/bashrc
          perl -v
          #  no share install for Alien::MSYS
          cpanm --notest Alien::MSYS
          #  ensure share install for gdal et al
          ALIEN_INSTALL_TYPE=share cpanm --notest --installdeps Alien::gdal
          ALIEN_INSTALL_TYPE=share cpanm --notest -v Alien::gdal
          #ALIEN_INSTALL_TYPE=share cpanm --notest -v https://github.com/shawnlaffan/perl-alien-gdal.git
          cpanm --notest Task::Biodiverse::NoGUI
          cpanm --notest ExtUtils::PkgConfig
          cpanm --notest ExtUtils::Depends
          cpanm --notest Gtk2
          cpanm --notest Gnome2::Canvas
          cpanm --notest Task::Biodiverse
          cpanm --notest PAR::Packer
          cpanm --notest File::BaseDir
          cpanm --notest File::Find::Rule
      
      - name: pack gdal script
        run: |
          source ~/perl5/perlbrew/etc/bashrc
          perl -v
          echo "========"
          perl pp_gdal_check.pl
          echo "========"
          echo Running packed exe
          ./pp_gdal_check
          echo "========"
          echo Running with /usr/local dirs out of the way
          sudo mv /usr/local/opt /usr/local/optx
          sudo mv /usr/local/Cellar /usr/local/Cellarx
          ./pp_gdal_check
          echo Putting /usr/local dirs back
          sudo mv /usr/local/optx /usr/local/opt
          sudo mv /usr/local/Cellarx /usr/local/Cellar
          echo "========"
          
      - name: Upload checkpp artefact
        uses: actions/upload-artifact@v1
        with:
          name: pp_gdal_check
          #path: ${DMG_FILE_NAME}
          path: ./pp_gdal_check
      
      - name: Test pack
        run: |
          source ~/perl5/perlbrew/etc/bashrc
          perl -v
          echo Running perl dynamic_libs check
          perl -e 'use 5.020; use Geo::GDAL::FFI; say join ":", Alien::gdal->dynamic_libs'
          pp -M Alien::gdal -M Alien::proj -M Alien::geos::af -M Alien::sqlite -M FFI::CheckLib -e 'use 5.020; use Alien::gdal; say join ":", Alien::gdal->dynamic_libs' -o checkpp
          echo Running checkpp dynamic libs check
          ./checkpp
          echo Running checkpp with /usr/local dirs out of the way
          sudo mv /usr/local/opt /usr/local/optx
          sudo mv /usr/local/Cellar /usr/local/Cellarx
          ./checkpp
          echo Putting /usr/local dirs back
          sudo mv /usr/local/optx /usr/local/opt
          sudo mv /usr/local/Cellarx /usr/local/Cellar
          
  
      - name: Upload checkpp artefact
        uses: actions/upload-artifact@v1
        with:
          name: checkpp
          #path: ${DMG_FILE_NAME}
          path: ./checkpp

      - name: Clone biodiverse repo
        run: git clone https://github.com/shawnlaffan/biodiverse.git
        
      #- name: Check Biodiverse can run
      #  run: |
      #    source ~/perl5/perlbrew/etc/bashrc
      #    prove -l biodiverse/t
      
      - name: Resize dmg file
        run: hdiutil resize -size 75MB ./images/Biodiverse.dmg
      
      - name: Run mmb3.pl
        run: |
          source ~/perl5/perlbrew/etc/bashrc
          perl bin/mmb3.pl -v -s biodiverse/bin/BiodiverseGUI.pl
        
      - name: Find dmg file
        run: |
          export DMG_FILE_NAME=`find ./builds -name Biodiverse-*.dmg -print`
          echo ${DMG_FILE_NAME}
          
      - name: Try to run the app
        run: |
          echo With system /usr/loca/opt in path
          BDV_PP_BUILDING=1 ./builds/Biodiverse.app/Contents/MacOS/BiodiverseGUI
          #  we need the brewed libs out of the way for this check
          echo Moving /usr/local/lib
          sudo mv /usr/local/lib /usr/local/libx
          BDV_PP_BUILDING=1 ./builds/Biodiverse.app/Contents/MacOS/BiodiverseGUI
          echo Returning /usr/local/lib
          sudo mv /usr/local/libx /usr/local/lib
          
        
      - name: Upload artefact
        uses: actions/upload-artifact@v1
        with:
          name: dmg-file
          #path: ${DMG_FILE_NAME}
          path: ./builds/Biodiverse-3.00-2.dmg
