name: macos

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

env:
  PERL5LIB: /Users/runner/perl5/lib/perl5
  PERL_LOCAL_LIB_ROOT: /Users/runner/perl5
  PERL_MB_OPT: --install_base /Users/runner/perl5
  PERL_MM_OPT: INSTALL_BASE=/Users/runner/perl5
  PERL_CPANM_OPT: -M https://www.cpan.org

jobs:
  perl:

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v4

      - name: Probe wd
        run: |
          pwd
          ls -l
          brew shellenv
          
      - name: Probe /usr/lib etc
        run: |
          echo /usr/local
          ls /usr/local
          echo /usr/lib/
          ls /usr/lib/
          echo /usr/lib/system
          ls /usr/lib/system
          

      - name: Install pkgconfig and fileicon
        run: |
          brew install pkgconfig
          brew install fileicon

      - name: Install GDAL and its deps
        run: brew install gdal
        
      #- name: Get lib names
      #  run: |
      #    find /usr/local/Cellar -name '*.dylib' -print
      #    find /usr/local/Cellar -name 'libxml2*.dylib' -print
      #    find /usr/local/Cellar -name '*lwgeom*.dylib' -print
      #    find /usr/local/Cellar -name 'libsqlite3*.dylib' -print
          
        
      - name: Install Gtk etc
        run: brew install gdk-pixbuf pango gtk+ gtk+3
      

      - name: Set up Perl
        run: |
          brew install perl
          curl https://cpanmin.us | perl - App::cpanminus -n
          # echo "##[add-path]/Users/runner/perl5/bin"
          echo "/Users/runner/perl5/bin" >> $GITHUB_PATH

      - name: perl -V
        run: perl -V

      - name: Prepare for cache
        run: |
          perl -V > perlversion.txt
          #  change the checksum so we refresh the cache
          echo 'with shared Alien installs' >> perlversion.txt
          ls -l perlversion.txt

      - name: Install libgnomecanvas 
        run: |
          eval "$(brew shellenv)"
          #  libgnomecanvas needs this
          cpanm XML::Parser 
          brew install libart intltool gettext
          \curl -L https://download.gnome.org/sources/libgnomecanvas/2.30/libgnomecanvas-2.30.3.tar.bz2 > lgc.tar.bz
          tar xf lgc.tar.bz
          cd libgnomecanvas-2.30.3
          \curl -L https://raw.githubusercontent.com/shawnlaffan/biodiverse/master/etc/libgnomecanvas.patch > libgnomecanvas.patch
          patch -d libgnomecanvas < libgnomecanvas.patch
          #  one should avoid installing into HOMEBREW_PATH on local builds, but CI is throw-away
          ./configure --disable-dependency-tracking --disable-static --prefix=$HOMEBREW_PREFIX --disable-glade
          make
          make install

      #- name: clear cache
      #  run: rm ~/perl5/${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}

      - name: Cache CPAN modules
        uses: actions/cache@v4
        if: "!cancelled()"
        with:
          path: ~/perl5
          key: ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}

      - name: Install cpan deps 
        run: |
          cpanm App::PP::Autolink
          which pp_autolink.pl
          which -a pp
          #  no share install for Alien::MSYS
          cpanm --notest Alien::MSYS
          #  ensure share install for gdal et al
          #ALIEN_INSTALL_TYPE=share cpanm --notest --installdeps Alien::gdal
          #ALIEN_INSTALL_TYPE=share cpanm --notest -v Alien::gdal
          #ALIEN_INSTALL_TYPE=share cpanm --notest -v https://github.com/shawnlaffan/perl-alien-gdal.git
          #cpanm --notest Task::Biodiverse::NoGUI
          cpanm --notest ExtUtils::PkgConfig
          cpanm --notest ExtUtils::Depends
          cpanm --notest Gtk2
          cpanm --notest Gnome2::Canvas
          cpanm --notest Task::Biodiverse
          cpanm --notest PAR::Packer
          cpanm --notest File::BaseDir
          cpanm --notest File::Find::Rule

      - name: Clone biodiverse repo
        run: | 
          git clone --depth=1 https://github.com/shawnlaffan/biodiverse.git
          cd biodiverse
          cpanm --installdeps .
          prove t/00-load.t
          cd -
        
      #- name: Check Biodiverse can run, except that it hangs
      #  run: prove -l biodiverse/t
      
      - name: Resize dmg file
        run: |
          hdiutil resize -size 100MB ./images/Biodiverse.dmg
          df -h
      
      - name: Run mmb3.pl
        run: |
          eval "$(brew shellenv)"
          export PATH=/Users/runner/perl5/bin:$PATH
          which -a pp
          echo $SHELL
          perl bin/mmb3.pl -v -s biodiverse/bin/BiodiverseGUI.pl
        
      - name: Find dmg file
        run: |
          export DMG_FILE_NAME=`find ./builds -name Biodiverse-*.dmg -print`
          echo ${DMG_FILE_NAME}
          
        
      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: dmg-file
          #path: ${DMG_FILE_NAME}
          path: ./builds/Biodiverse-*.dmg
